# Generated by Django 3.2 on 2021-12-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='name',
            field=models.CharField(default='no name', max_length=10000),
        ),
    ]
